### ISSUE TITLE
Would you mind if I asked you guys to commit the code?

### ISSUE THREAD

**Issue by matyascorvinus** [hsndbk4/BARRE#1]
Dear Mr Hassan Dbouk and Mr Naresh R. Shanbhag,

Would you mind if I asked you guys to commit the code? I would love to implement some new additional security measures for the ensemble models on top of this paper's achievement.

Sincerely yours,
Truong Dang Quang

**Comment by hsndbk4** [comment]
Thank you for reminding us! The code has been uploaded.

Best,
Hassan

**Comment by matyascorvinus** [comment]
Thank you so much for your time.
